#!/usr/bin/env bash
#
# Build the single-file edition.
#
#   tools/build-standalone.sh
#
# Produces asset-manager.html: one self-contained file that runs by
# double-clicking it, with no server and no network.
#
# Why this exists: a browser refuses to load `<script type="module" src="...">`
# over file:// (it is a cross-origin request from an opaque origin), so the
# modular index.html shows a blank page when opened from disk. Inlining
# everything into one classic script sidesteps that entirely.
#
# The bundle is a plain concatenation inside one IIFE. It works because every
# module here uses only single-line named imports and simple `export const` /
# `export function` declarations, and no two modules declare the same top-level
# name. check_collisions() enforces that second point rather than trusting it.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

OUT="asset-manager.html"

# Dependency order. Data and vendor blobs first, then core, then tools, then the
# shell, which calls boot() on the last line.
MODULES=(
  assets/js/data/i18n-he.js
  assets/js/data/about.js
  assets/js/data/changelog.js
  assets/js/vendor/sheet-worker-source.js
  assets/js/workers/crop-worker-source.js
  assets/js/core/version.js
  assets/js/core/dom.js
  assets/js/core/prefs.js
  assets/js/core/i18n.js
  assets/js/core/ui.js
  assets/js/core/files.js
  assets/js/core/image.js
  assets/js/core/sheet.js
  assets/js/core/sanitize.js
  assets/js/core/update.js
  assets/js/tools/cropper.js
  assets/js/tools/resizer.js
  assets/js/tools/cleaner.js
  assets/js/tools/dragon.js
  assets/js/tools/price.js
  assets/js/tools/about.js
  assets/js/main.js
)

check_collisions() {
  local dupes
  dupes="$(for f in "${MODULES[@]}"; do
    grep -hoE '^(export )?(async )?(const|let|var|function|class) [A-Za-z_$][A-Za-z0-9_$]*' "$f" \
      | sed -E 's/^(export )?(async )?(const|let|var|function|class) //'
  done | sort | uniq -d)"

  if [ -n "$dupes" ]; then
    echo "error: modules declare the same top-level name, so they cannot share one scope:" >&2
    echo "$dupes" >&2
    exit 1
  fi
}

# Every module must be listed, or the bundle silently loses code.
check_coverage() {
  local found missing
  found="$(printf '%s\n' "${MODULES[@]}" | sort)"
  missing="$(find assets/js -name '*.js' | sed 's|\\|/|g' | sort | comm -23 - <(echo "$found"))"

  if [ -n "$missing" ]; then
    echo "error: these modules exist but are not in the bundle list:" >&2
    echo "$missing" >&2
    exit 1
  fi
}

strip_module_syntax() {
  # Drop single-line named imports; turn exported declarations into plain ones.
  sed -E \
    -e '/^import[[:space:]].*from[[:space:]].*;[[:space:]]*$/d' \
    -e 's/^export (async )?(const|let|var|function|class)([[:space:]])/\1\2\3/' \
    "$1"
}

check_collisions
check_coverage

VERSION="$(grep -oE "APP_VERSION = '[^']+'" assets/js/core/version.js | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")"

{
  # Everything above the stylesheet link, taken from the real index.html so the
  # two editions cannot drift apart. The manifest link is dropped: it points at a
  # sibling file that does not exist next to a standalone copy.
  sed -n '1,/<link rel="stylesheet"/p' index.html \
    | sed '$d' \
    | grep -v 'rel="manifest"'

  echo '    <style>'
  cat assets/css/app.css
  echo '    </style>'
  echo '  </head>'
  echo ''
  echo '  <body>'
  echo '    <noscript>'
  echo '      <p style="padding: 24px; font-family: system-ui, sans-serif;">'
  echo '        Asset Manager needs JavaScript. Everything runs inside your browser;'
  echo '        nothing is sent to a server.'
  echo '      </p>'
  echo '    </noscript>'
  echo ''
  echo "    <!-- Single-file build $VERSION. Generated by tools/build-standalone.sh -->"
  echo "    <!-- Do not edit by hand: change assets/ and rebuild. -->"
  echo '    <script>'
  echo '(function () {'
  echo '"use strict";'

  for module in "${MODULES[@]}"; do
    echo ""
    echo "/* ---- $module ---- */"
    strip_module_syntax "$module"
  done

  echo '})();'
  echo '    </script>'
  echo '  </body>'
  echo '</html>'
} > "$OUT"

bytes="$(wc -c < "$OUT" | tr -d ' ')"
echo "wrote $OUT ($bytes bytes, version $VERSION)"
